// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Project_Bullion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsermanagementClient is the client API for Usermanagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsermanagementClient interface {
	CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type usermanagementClient struct {
	cc grpc.ClientConnInterface
}

func NewUsermanagementClient(cc grpc.ClientConnInterface) UsermanagementClient {
	return &usermanagementClient{cc}
}

func (c *usermanagementClient) CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/usermgmt.usermanagement/createNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsermanagementServer is the server API for Usermanagement service.
// All implementations must embed UnimplementedUsermanagementServer
// for forward compatibility
type UsermanagementServer interface {
	CreateNewUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedUsermanagementServer()
}

// UnimplementedUsermanagementServer must be embedded to have forward compatible implementations.
type UnimplementedUsermanagementServer struct {
}

func (UnimplementedUsermanagementServer) CreateNewUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewUser not implemented")
}
func (UnimplementedUsermanagementServer) mustEmbedUnimplementedUsermanagementServer() {}

// UnsafeUsermanagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsermanagementServer will
// result in compilation errors.
type UnsafeUsermanagementServer interface {
	mustEmbedUnimplementedUsermanagementServer()
}

func RegisterUsermanagementServer(s grpc.ServiceRegistrar, srv UsermanagementServer) {
	s.RegisterService(&Usermanagement_ServiceDesc, srv)
}

func _Usermanagement_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsermanagementServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgmt.usermanagement/createNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsermanagementServer).CreateNewUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// Usermanagement_ServiceDesc is the grpc.ServiceDesc for Usermanagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usermanagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermgmt.usermanagement",
	HandlerType: (*UsermanagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createNewUser",
			Handler:    _Usermanagement_CreateNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgmt/usermgmt.proto",
}
